@echo off
cd vagony
copy /b krystal4.scr+krystal5.scr+krystal6.scr+krystal7.scr  vagony01.scr
copy /b vagony01.scr+koruna4.scr+koruna5.scr+koruna6.scr+koruna7.scr  vagony02.scr
copy /b vagony02.scr+strom4.scr+strom5.scr+strom6.scr+strom7.scr  vagony03.scr
copy /b vagony03.scr+jablko4.scr+jablko5.scr+jablko6.scr+jablko7.scr  vagony04.scr
copy /b vagony04.scr+krava4.scr+krava5.scr+krava6.scr+krava7.scr  vagony05.scr
copy /b vagony05.scr+tresne4.scr+tresne5.scr+tresne6.scr+tresne7.scr  vagony06.scr
copy /b vagony06.scr+rybnik4.scr+rybnik5.scr+rybnik6.scr+rybnik7.scr  vagony07.scr
copy /b vagony07.scr+zirafa4.scr+zirafa5.scr+zirafa6.scr+zirafa7.scr  vagony08.scr
copy /b vagony08.scr+zmrzlin4.scr+zmrzlin5.scr+zmrzlin6.scr+zmrzlin7.scr  vagony09.scr
copy /b vagony09.scr+dort4.scr+dort5.scr+dort6.scr+dort7.scr  vagony10.scr
copy /b vagony10.scr+pocitac4.scr+pocitac5.scr+pocitac6.scr+pocitac7.scr  vagony11.scr
copy /b vagony11.scr+auto4.scr+auto5.scr+auto6.scr+auto7.scr  vagony12.scr
copy /b vagony12.scr+balon4.scr+balon5.scr+balon6.scr+balon7.scr  vagony13.scr
copy /b vagony13.scr+budik4.scr+budik5.scr+budik6.scr+budik7.scr  vagony14.scr
copy /b vagony14.scr+slon4.scr+slon5.scr+slon6.scr+slon7.scr  vagony15.scr
copy /b vagony15.scr+vino4.scr+vino5.scr+vino6.scr+vino7.scr  vagony16.scr
copy /b vagony16.scr+penize4.scr+penize5.scr+penize6.scr+penize7.scr  vagony17.scr
copy /b vagony17.scr+letadlo4.scr+letadlo5.scr+letadlo6.scr+letadlo7.scr  vagony18.scr

copy vagony18.scr ..\vagony.scr

del vagony01.scr
del vagony02.scr
del vagony03.scr
del vagony04.scr
del vagony05.scr
del vagony06.scr
del vagony07.scr
del vagony08.scr
del vagony09.scr
del vagony10.scr
del vagony11.scr
del vagony12.scr
del vagony13.scr
del vagony14.scr
del vagony15.scr
del vagony16.scr
del vagony17.scr
del vagony18.scr

cd ..
